### ISSUE TITLE
Default config not set

### ISSUE THREAD

**Issue by JordanVincent** [pgrippi/ember-cli-google-analytics#6]
When updating to v1.3.0, if ```ENV.googleAnalytics.tracker``` is not specified it won't trigger pageviews.

Fix:
```javascript
ENV.googleAnalytics = {
      webPropertyId: 'UA-XXXXXXXX-1',
      tracker : 'analytics.js'
 }
```

**Comment by pgrippi** [comment]
Whoops, I tagged v1.3.1 but I forgot to publish it on npm. It should be there now, please try upgrading and let me know if it fixed the issue.

**Comment by JordanVincent** [comment]
Yes, it's fixed. Thank you!
